MDScreen:
    MDBoxLayout:
        orientation: 'vertical'
        MDBoxLayout:
            size_hint_y: .1
            
            MDLabel:
                text: 'COLOR PICKER'
                halign: 'center'
                theme_font_size:"Custom"
                font_size: "50dp"
        
        MDBoxLayout:
            size_hint_y: .8
            
        
        MDBoxLayout:
            id:picker_box
            size_hint_y: .1
            MDLabel:
                id:picker_text
                text:"COLOR"
                halign: 'center'
                theme_font_size:"Custom"
                font_size: "50dp"



        
    