MDScreen:
    MDBoxLayout:
        orientation: 'vertical'
        id:picker_box
        MDBoxLayout:
            size_hint_y: .1
            
            MDLabel:
                text: 'COLOR PICKER'
                halign: 'center'
                theme_font_size:"Custom"
                font_size: "50dp"
        
        MDBoxLayout:
            size_hint_y: .8
            
        
        MDBoxLayout:
            
            size_hint_y: .1
            canvas: 
                Color: 
                    rgba: (.2,.3,.4,.1)
                Rectangle: 
                    size:self.size
                    pos:self.pos
            MDLabel:
                id:picker_text
                text:"COLOR"
                halign: 'center'
                theme_font_size:"Custom"
                font_size: "50dp"

    MDRaisedButton:
        text: 'Close'
        pos_hint:{"center_x":.5}
        on_release: app.close_app()



        
    